sharding:
  jdbc:
    datasource:
      names: ds0,ds1
      ds0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://thunderclap.cn:3306/ds0
        username: zhh
        password: 123456
      ds1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://thunderclap.cn:3306/ds1
        username: zhh
        password: 123456

    config:
      sharding:
        default-database-strategy:
          inline:
            sharding-column: user_id
            algorithm-expression: ds$->{user_id % 2}
        tables:
          t_user:
            actual-data-nodes: ds$->{0..1}.t_user$->{0..1}
            key-generator-column-name: user_id
            key-generator-class-name: io.shardingsphere.core.keygen.DefaultKeyGenerator
            table-strategy:
              inline:
                sharding-column: user_id
                algorithm-expression: t_user$->{user_id % 2}